version: '3.8'

services:
  
  sqlserver:
    container_name: booklibrary-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: localhost
    ports:
    - 1433:1433
    networks:
        - booklibrary-net
    environment:
    - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    - MSSQL_PID=${MSSQL_PID}
    - ACCEPT_EULA=Y
    
networks:
  booklibrary-net:
    name: docker-compose.env/booklibrary-net
